In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dengue_weather.csv')
df.head()

,idx_city,week,count,Latitude,Longitude,tavg,tmin,tmax,prcp,wdir,wspd,pres,elevation
0,COLOMBIA_AMAZONAS_LETICIA,1/2/2023,7,-4.212921,-69.942596,25.228571,22.985714,29.171429,8.528571,56.000000,4.800000,1010.985714,81
1,COLOMBIA_AMAZONAS_LETICIA,1/9/2023,11,-4.212921,-69.942596,25.000000,22.328571,29.042857,12.128571,207.857143,4.228571,1010.957143,81
2,COLOMBIA_AMAZONAS_LETICIA,1/16/2023,5,-4.212921,-69.942596,24.942857,22.257143,28.714286,12.971429,118.857143,3.800000,1010.814286,81
3,COLOMBIA_AMAZONAS_LETICIA,1/23/2023,8,-4.212921,-69.942596,25.657143,22.771429,30.471429,12.671429,200.857143,4.200000,1009.657143,81
4,COLOMBIA_AMAZONAS_LETICIA,1/30/2023,17,-4.212921,-69.942596,24.871429,22.328571,29.228571,16.728571,111.714286,4.028571,1010.857143,81

In [3]:
df['date'] = pd.to_datetime(df['week'])

In [4]:
df.columns

Index(['idx_city', 'week', 'count', 'Latitude', 'Longitude', 'tavg', 'tmin',
       'tmax', 'prcp', 'wdir', 'wspd', 'pres', 'elevation', 'date'],
      dtype='object')

In [5]:
# vars to lag
vars_to_lag = ['tavg', 'tmin', 'tmax', 'prcp', 'wdir', 'wspd', 'pres']
# group by idx_city to lag variables
for var in vars_to_lag:
    df[f'{var}_lag1'] = df.groupby('idx_city')[var].shift(1)

In [6]:
df.head()

,idx_city,week,count,Latitude,Longitude,tavg,tmin,tmax,prcp,wdir,...,pres,elevation,date,tavg_lag1,tmin_lag1,tmax_lag1,prcp_lag1,wdir_lag1,wspd_lag1,pres_lag1
0,COLOMBIA_AMAZONAS_LETICIA,1/2/2023,7,-4.212921,-69.942596,25.228571,22.985714,29.171429,8.528571,56.000000,...,1010.985714,81,2023-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COLOMBIA_AMAZONAS_LETICIA,1/9/2023,11,-4.212921,-69.942596,25.000000,22.328571,29.042857,12.128571,207.857143,...,1010.957143,81,2023-01-09,25.228571,22.985714,29.171429,8.528571,56.000000,4.800000,1010.985714
2,COLOMBIA_AMAZONAS_LETICIA,1/16/2023,5,-4.212921,-69.942596,24.942857,22.257143,28.714286,12.971429,118.857143,...,1010.814286,81,2023-01-16,25.000000,22.328571,29.042857,12.128571,207.857143,4.228571,1010.957143
3,COLOMBIA_AMAZONAS_LETICIA,1/23/2023,8,-4.212921,-69.942596,25.657143,22.771429,30.471429,12.671429,200.857143,...,1009.657143,81,2023-01-23,24.942857,22.257143,28.714286,12.971429,118.857143,3.800000,1010.814286
4,COLOMBIA_AMAZONAS_LETICIA,1/30/2023,17,-4.212921,-69.942596,24.871429,22.328571,29.228571,16.728571,111.714286,...,1010.857143,81,2023-01-30,25.657143,22.771429,30.471429,12.671429,200.857143,4.200000,1009.657143

In [7]:
df.dropna(inplace=True)  # Drop rows with NaN values after lagging
df.to_csv('dengue_weather_lagged.csv', index=False)  # Save the modified DataFrame