# Meteostat

In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
import folium
from meteostat import Stations, Daily, Point
from datetime import datetime
import time
import re
from unidecode import unidecode
import matplotlib.pyplot as plt

In [2]:
# Initialize geocoder
geolocator = Nominatim(user_agent="weather_locator")

## Clean Cities

In [3]:
df_dengue = pd.read_csv('silver/dengue_city_geolocated.csv')
df_dengue.head()

,SEMANA,ANO,country,state,city,count,idx_city,Latitude,Longitude,date,week
0,1,2007,colombia,arauca,arauca,2,COLOMBIA_ARAUCA_ARAUCA,7.085199,-70.757776,2007-01-07,07-01-2007
1,1,2007,colombia,arauca,saravena,1,COLOMBIA_ARAUCA_SARAVENA,6.906819,-71.836133,2007-01-07,07-01-2007
2,1,2007,colombia,atlantico,baranoa,7,COLOMBIA_ATLANTICO_BARANOA,10.793582,-74.915216,2007-01-07,07-01-2007
3,1,2007,colombia,atlantico,barranquilla,23,COLOMBIA_ATLANTICO_BARRANQUILLA,11.010192,-74.823179,2007-01-07,07-01-2007
4,1,2007,colombia,atlantico,galapa,2,COLOMBIA_ATLANTICO_GALAPA,10.896866,-74.885961,2007-01-07,07-01-2007

In [4]:
df_dengue_og = df_dengue.copy()

In [5]:
df_dengue = df_dengue[df_dengue['ANO'] == 2023]
df_dengue.drop(columns = ['SEMANA', 'ANO', 'week'], inplace=True)
df_dengue['date'] = pd.to_datetime(df_dengue['date'])

In [6]:
df_dengue

,country,state,city,count,idx_city,Latitude,Longitude,date
131554,aruba,exterior,exterior_aruba,1,ARUBA_EXTERIOR_EXTERIOR_ARUBA,12.501363,-69.961848,2023-01-08
131555,brasil,exterior,exterior_brasil,1,BRASIL_EXTERIOR_EXTERIOR_BRASIL,-10.333333,-53.200000,2023-01-08
131556,colombia,amazonas,leticia,7,COLOMBIA_AMAZONAS_LETICIA,-4.212921,-69.942596,2023-01-08
131557,colombia,antioquia,apartado,7,COLOMBIA_ANTIOQUIA_APARTADO,7.884901,-76.622746,2023-01-08
131558,colombia,antioquia,caracoli,1,COLOMBIA_ANTIOQUIA_CARACOLI,6.409276,-74.756698,2023-01-08
...,...,...,...,...,...,...,...,...
147043,colombia,vaupes,mitu,8,COLOMBIA_VAUPES_MITU,1.253850,-70.234558,2023-12-31
147044,colombia,vichada,puerto carreno,1,COLOMBIA_VICHADA_PUERTO CARREÑO,6.190923,-67.484189,2023-12-31
147045,comoras,exterior,exterior_comoras,1,COMORAS_EXTERIOR_EXTERIOR_COMORAS,-12.204518,44.283296,2023-12-31
147046,haiti,exterior,exterior_haiti,1,HAITÍ_EXTERIOR_EXTERIOR_HAITÍ,19.139995,-72.357097,2023-12-31
147047,venezuela,exterior,exterior_venezuela,3,VENEZUELA_EXTERIOR_EXTERIOR_VENEZUELA,8.001871,-66.110932,2023-12-31

In [7]:
df = df_dengue.copy()

In [8]:
# Function to clean text
def clean_text(text):
    text = str(text).lower()               # Lowercase
    text = unidecode(text)                 # Remove accents
    text = re.sub(r'[^\w\s]', '', text)    # Remove punctuation
    text = re.sub(r'\s+', ' ', text)       # Normalize whitespace
    return text.strip()

# Apply to relevant columns
# Apply to relevant columns
df['country'] = df['country'].apply(clean_text)
df['state'] = df['state'].apply(clean_text)
df['city'] = df['city'].apply(clean_text)

# Optional: remove duplicate cities (if any)
df.drop_duplicates(subset=['city', 'state', 'country'], inplace=True)

In [9]:
df

,country,state,city,count,idx_city,Latitude,Longitude,date
131554,aruba,exterior,exterior_aruba,1,ARUBA_EXTERIOR_EXTERIOR_ARUBA,12.501363,-69.961848,2023-01-08
131555,brasil,exterior,exterior_brasil,1,BRASIL_EXTERIOR_EXTERIOR_BRASIL,-10.333333,-53.200000,2023-01-08
131556,colombia,amazonas,leticia,7,COLOMBIA_AMAZONAS_LETICIA,-4.212921,-69.942596,2023-01-08
131557,colombia,antioquia,apartado,7,COLOMBIA_ANTIOQUIA_APARTADO,7.884901,-76.622746,2023-01-08
131558,colombia,antioquia,caracoli,1,COLOMBIA_ANTIOQUIA_CARACOLI,6.409276,-74.756698,2023-01-08
...,...,...,...,...,...,...,...,...
146890,colombia,huila,teruel,1,COLOMBIA_HUILA_TERUEL,2.741633,-75.568345,2023-12-31
146951,colombia,quindio,buenavista,1,COLOMBIA_QUINDIO_BUENAVISTA,4.359948,-75.738723,2023-12-31
146956,colombia,risaralda,belen de umbria,1,COLOMBIA_RISARALDA_BELEN DE UMBRIA,5.200909,-75.868993,2023-12-31
147045,comoras,exterior,exterior_comoras,1,COMORAS_EXTERIOR_EXTERIOR_COMORAS,-12.204518,44.283296,2023-12-31
147046,haiti,exterior,exterior_haiti,1,HAITÍ_EXTERIOR_EXTERIOR_HAITÍ,19.139995,-72.357097,2023-12-31

# Geocode

In [10]:
# Function to geocode city
def geocode_city(city, depto, country):
    query = f"{city}, {depto}, {country}"
    try:
        location = geolocator.geocode(query)
        if location:
            return location.latitude, location.longitude
    except Exception as e:
        print(f"Geocoding error for {query}: {e}")
    return None, None

# Meteo

In [11]:
cities_df = df[['city', 'state', 'country', 'Latitude', 'Longitude', 'idx_city']].copy().drop_duplicates().reset_index(drop=True)

In [12]:
cities_df.dropna(subset = ['Latitude', 'Longitude'], inplace=True)

In [13]:
cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 802 entries, 0 to 810
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       802 non-null    object
 1   state      802 non-null    object
 2   country    802 non-null    object
 3   Latitude   802 non-null    float64
 4   Longitude  802 non-null    float64
 5   idx_city   802 non-null    object
dtypes: float64(2), object(4)
memory usage: 43.9+ KB

In [29]:
cities_df.to_csv('meteo_colombia/cities_geolocated.csv', index=False)

In [14]:
# Define the date range
start = datetime(2023, 1, 1)
end = datetime(2023, 12, 31)

In [15]:
# create dir if not exist 'meteo_colombia/cities/'
import os
if not os.path.exists('meteo_colombia/cities/'):
    os.makedirs('meteo_colombia/cities/')

In [16]:
import time
from tqdm import tqdm

In [23]:
cities_df.reset_index(drop=True, inplace=True)

In [24]:
cities_df[84:85]

     city  state   country  Latitude  Longitude              idx_city
84  lloro  choco  colombia  5.584484 -76.372565  COLOMBIA_CHOCO_LLORO

In [25]:
range(84,len(cities_df))

range(84, 802)

In [27]:
# got error at 84, go from 84 to the end
for i in tqdm(range(84,len(cities_df))):
    
    lat = cities_df['Latitude'][i]
    lon = cities_df['Longitude'][i]
    # if lat or lon is None, skip the city
    if lat is None or lon is None:
        print(f"Skipping {cities_df['City'][i]} due to missing coordinates.")
        continue
    # create point for city
    city = Point(lat, lon)

    # Get daily data for
    data = Daily(city, start, end)
    data = data.fetch()
    # save data to csv in 'meteo_colombia/cities/' folder
    data.to_csv(f'meteo_colombia/cities/{cities_df["idx_city"][i]}.csv')
    time.sleep(5)

  0%|          | 0/718 [00:00<?, ?it/s]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  1%|          | 6/718 [00:30<1:00:40,  5.11s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  1%|          | 7/718 [00:36<1:01:41,  5.21s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  3%|▎         | 23/718 [01:57<58:54,  5.09s/it]  FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  4%|▍         | 31/718 [02:38<58:29,  5.11s/it]  FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  6%|▌         | 40/718 [03:25<57:43,  5.11s/it]  FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  6%|▋         | 46/718 [03:56<57:08,  5.10s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  7%|▋         | 49/718 [04:12<57:40,  5.17s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  9%|▉         | 64/718 [05:29<55:31,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  9%|▉         | 66/718 [05:39<56:32,  5.20s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 12%|█▏        | 86/718 [07:22<53:35,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 12%|█▏        | 87/718 [07:27<55:44,  5.30s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 13%|█▎        | 90/718 [07:43<54:31,  5.21s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▎        | 97/718 [08:19<53:02,  5.12s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▍        | 100/718 [08:35<53:00,  5.15s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▍        | 101/718 [08:41<55:48,  5.43s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▍        | 102/718 [08:46<55:27,  5.40s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▍        | 103/718 [08:52<55:53,  5.45s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 14%|█▍        | 104/718 [08:58<55:59,  5.47s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 17%|█▋        | 125/718 [10:45<50:20,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 18%|█▊        | 132/718 [11:21<49:55,  5.11s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 20%|█▉        | 141/718 [12:07<48:56,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 20%|█▉        | 143/718 [12:17<49:17,  5.14s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 21%|██        | 151/718 [12:58<48:12,  5.10s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 22%|██▏       | 158/718 [13:34<47:41,  5.11s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 35%|███▌      | 252/718 [21:32<39:18,  5.06s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 36%|███▋      | 261/718 [22:19<38:54,  5.11s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 50%|█████     | 359/718 [30:38<30:39,  5.13s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 52%|█████▏    | 372/718 [31:46<29:38,  5.14s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 55%|█████▌    | 395/718 [33:45<27:34,  5.12s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 57%|█████▋    | 409/718 [34:57<26:24,  5.13s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 60%|██████    | 432/718 [36:55<24:13,  5.08s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 62%|██████▏   | 442/718 [37:47<23:26,  5.10s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 69%|██████▉   | 497/718 [42:27<18:43,  5.08s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 79%|███████▉  | 568/718 [48:28<12:43,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 85%|████████▌ | 611/718 [52:07<09:04,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 93%|█████████▎| 665/718 [56:42<04:30,  5.11s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 93%|█████████▎| 670/718 [57:08<04:05,  5.12s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 94%|█████████▍| 677/718 [57:44<03:28,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
 95%|█████████▌| 684/718 [58:19<02:52,  5.06s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
100%|█████████▉| 716/718 [1:01:03<00:10,  5.09s/it]FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
100%|██████████| 718/718 [1:01:13<00:00,  5.12s/it]