# Wrangle Weather Data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df_not_empty = pd.read_csv('meteo_colombia/cities_dengue_not_empty.csv')
df_not_empty

,city,state,country,Latitude,Longitude,idx_city,status,nearest_city
0,exterior_aruba,exterior,aruba,12.501363,-69.961848,ARUBA_EXTERIOR_EXTERIOR_ARUBA,not_empty,ARUBA_EXTERIOR_EXTERIOR_ARUBA
1,leticia,amazonas,colombia,-4.212921,-69.942596,COLOMBIA_AMAZONAS_LETICIA,not_empty,COLOMBIA_AMAZONAS_LETICIA
2,apartado,antioquia,colombia,7.884901,-76.622746,COLOMBIA_ANTIOQUIA_APARTADO,not_empty,COLOMBIA_ANTIOQUIA_APARTADO
3,carepa,antioquia,colombia,7.798452,-76.746039,COLOMBIA_ANTIOQUIA_CAREPA,not_empty,COLOMBIA_ANTIOQUIA_CAREPA
4,chigorodo,antioquia,colombia,7.612938,-76.638426,COLOMBIA_ANTIOQUIA_CHIGORODO,not_empty,COLOMBIA_ANTIOQUIA_CHIGORODO
...,...,...,...,...,...,...,...,...
265,cajibio,cauca,colombia,2.623169,-76.569350,COLOMBIA_CAUCA_CAJIBIO,not_empty,COLOMBIA_CAUCA_CAJIBIO
266,rionegro,antioquia,colombia,6.153617,-75.374169,COLOMBIA_ANTIOQUIA_RIONEGRO,not_empty,COLOMBIA_ANTIOQUIA_RIONEGRO
267,silvia,cauca,colombia,2.611544,-76.378424,COLOMBIA_CAUCA_SILVIA,not_empty,COLOMBIA_CAUCA_SILVIA
268,buenavista,quindio,colombia,4.359948,-75.738723,COLOMBIA_QUINDIO_BUENAVISTA,not_empty,COLOMBIA_QUINDIO_BUENAVISTA
269,exterior_comoras,exterior,comoras,-12.204518,44.283296,COMORAS_EXTERIOR_EXTERIOR_COMORAS,not_empty,COMORAS_EXTERIOR_EXTERIOR_COMORAS

In [5]:
df_temp.columns

Index(['time', 'tavg', 'tmin', 'tmax', 'prcp', 'snow', 'wdir', 'wspd', 'wpgt',
       'pres', 'tsun'],
      dtype='object')

In [15]:
# create dir if not exists called cties_weekly
if not os.path.exists('meteo_colombia/cities_weekly'):
    os.makedirs('meteo_colombia/cities_weekly')

In [18]:
# loop over idx_city to open files in folder
path = 'meteo_colombia/cities/'
output_path = 'meteo_colombia/cities_weekly/'
cols_keep = ['time', 'tavg', 'tmin', 'tmax', 'prcp', 'wdir', 'wspd', 'pres']
cols_mean = [ 'tavg', 'tmin', 'tmax', 'prcp', 'wdir', 'wspd', 'pres']
for idx_city in df_not_empty['idx_city']:
    df_temp = pd.read_csv(path + str(idx_city) + '.csv')
    df_temp = df_temp[cols_keep]
    df_temp['date'] = pd.to_datetime(df_temp['time'])
    # get week from date as date format
    df_temp['week'] = df_temp['date'].dt.to_period('W').apply(lambda r: r.start_time)
    # group by week and get mean of cols_keep
    df_temp.drop(columns=['time'], inplace=True)
    df_temp_g = df_temp.groupby('week')[cols_mean].mean().reset_index()
    # rename week to date
    #df_temp_g.rename(columns={'week': 'date'}, inplace=True)
    # save to csv
    df_temp_g.to_csv(output_path + str(idx_city) + '.csv', index=False)

In [19]:
df_temp_g

,week,tavg,tmin,tmax,prcp,wdir,wspd,pres
0,2022-12-26,27.100000,25.400000,29.200000,1.600000,52.000000,12.200000,1014.000000
1,2023-01-02,26.700000,25.300000,28.771429,4.742857,62.428571,13.914286,1013.657143
2,2023-01-09,26.671429,25.342857,28.357143,6.785714,221.571429,8.700000,1012.600000
3,2023-01-16,27.042857,25.542857,28.828571,15.928571,269.714286,24.742857,1010.228571
4,2023-01-23,27.514286,26.428571,28.742857,18.285714,329.714286,32.328571,1009.314286
5,2023-01-30,27.357143,25.885714,29.542857,5.200000,240.142857,11.057143,1011.314286
6,2023-02-06,26.957143,25.214286,29.271429,3.857143,73.428571,16.571429,1011.500000
7,2023-02-13,27.714286,26.100000,29.742857,3.014286,77.285714,10.700000,1011.257143
8,2023-02-20,27.028571,25.671429,28.857143,6.900000,212.000000,14.628571,1012.314286
9,2023-02-27,27.700000,26.385714,29.528571,3.385714,125.285714,20.971429,1013.014286
10,2023-03-06,28.442857,27.300000,30.085714,0.857143,198.000000,20.742857,1010.442857
11,2023-03-13,27.428571,25.742857,29.700000,3.757143,118.285714,10.985714,1010.771429
12,2023-03-20,27.371429,25.657143,29.871429,7.285714,92.285714,15.657143,1011.271429
13,2023-03-27,27.314286,25.728571,29.157143,4.514286,128.285714,13.085714,1011.400000
14,2023-04-03,27.057143,25.500000,28.942857,5.457143,103.571429,14.242857,1011.814286
15,2023-04-10,27.514286,25.985714,29.571429,2.385714,112.571429,12.728571,1012.442857
16,2023-04-17,28.014286,26.271429,30.028571,2.085714,113.428571,15.228571,1010.842857
17,2023-04-24,27.671429,25.985714,29.742857,1.642857,171.428571,19.285714,1011.671429
18,2023-05-01,27.042857,25.514286,28.900000,1.428571,188.571429,20.800000,1014.557143
19,2023-05-08,27.185714,25.600000,29.128571,1.071429,154.571429,15.285714,1015.028571
20,2023-05-15,27.100000,25.542857,29.371429,0.628571,136.000000,17.714286,1015.171429
21,2023-05-22,26.742857,25.128571,28.957143,0.485714,175.285714,18.357143,1015.628571
22,2023-05-29,26.685714,24.728571,28.971429,0.800000,124.142857,14.885714,1016.571429
23,2023-06-05,26.600000,24.942857,28.885714,0.957143,150.000000,14.085714,1016.457143
24,2023-06-12,25.900000,24.357143,28.342857,0.857143,163.142857,13.442857,1015.900000
25,2023-06-19,25.814286,24.242857,27.900000,0.585714,189.857143,20.857143,1015.657143
26,2023-06-26,25.671429,24.442857,27.571429,0.728571,145.571429,18.871429,1018.057143
27,2023-07-03,25.942857,24.600000,27.928571,0.042857,124.571429,20.857143,1018.657143
28,2023-07-10,25.457143,24.228571,27.042857,0.214286,185.857143,25.585714,1017.385714
29,2023-07-17,25.600000,24.328571,27.400000,0.314286,164.285714,22.900000,1018.700000
30,2023-07-24,25.371429,23.928571,27.442857,0.414286,116.714286,18.671429,1018.028571
31,2023-07-31,25.528571,24.100000,27.442857,0.442857,145.571429,22.157143,1019.771429
32,2023-08-07,24.900000,23.457143,26.685714,1.357143,215.857143,20.042857,1017.785714
33,2023-08-14,25.671429,24.300000,27.828571,1.214286,257.000000,13.371429,1016.842857
34,2023-08-21,25.857143,24.228571,28.400000,0.928571,135.428571,12.671429,1015.914286
35,2023-08-28,25.700000,24.257143,27.585714,1.214286,169.000000,16.000000,1017.671429
36,2023-09-04,25.800000,24.314286,27.928571,1.557143,219.285714,12.257143,1015.900000
37,2023-09-11,25.757143,24.385714,27.957143,0.571429,65.571429,15.200000,1016.014286
38,2023-09-18,25.985714,24.628571,27.928571,2.800000,100.714286,13.842857,1015.728571
39,2023-09-25,26.028571,24.628571,28.100000,0.771429,67.571429,17.028571,1016.257143
40,2023-10-02,26.557143,24.885714,28.700000,1.671429,83.285714,16.600000,1016.100000
41,2023-10-09,26.700000,25.242857,28.628571,1.300000,59.571429,19.257143,1014.585714
42,2023-10-16,27.300000,25.800000,29.557143,0.542857,74.428571,20.042857,1014.514286
43,2023-10-23,27.571429,26.200000,29.600000,0.057143,76.428571,24.657143,1013.300000
44,2023-10-30,27.685714,25.914286,29.814286,1.757143,93.285714,18.585714,1013.128571
45,2023-11-06,27.814286,26.400000,29.771429,2.185714,78.714286,21.685714,1013.785714
46,2023-11-13,28.200000,26.771429,29.985714,3.157143,115.285714,17.857143,1013.700000
47,2023-11-20,28.214286,27.000000,29.971429,4.100000,94.428571,15.842857,1012.528571
48,2023-11-27,27.842857,26.542857,29.328571,3.857143,134.571429,13.957143,1011.228571
49,2023-12-04,27.085714,25.600000,28.728571,10.314286,88.285714,18.114286,1012.314286
50,2023-12-11,28.500000,27.400000,30.171429,1.928571,134.857143,13.157143,1012.142857
51,2023-12-18,28.628571,27.214286,30.114286,4.828571,292.142857,10.885714,1011.942857
52,2023-12-25,28.857143,27.157143,30.628571,1.357143,27.857143,14.314286,1011.685714