# Dengue Data with weather

In [43]:
import pandas as pd
import numpy as np
import os

In [44]:
df_dengue = pd.read_csv('silver/dengue_city_geolocated.csv')
df_dengue = df_dengue[df_dengue['ANO'] == 2023]
df_dengue

,SEMANA,ANO,country,state,city,count,idx_city,Latitude,Longitude,date,week
131554,1,2023,aruba,exterior,exterior_aruba,1,ARUBA_EXTERIOR_EXTERIOR_ARUBA,12.501363,-69.961848,2023-01-08,08-01-2023
131555,1,2023,brasil,exterior,exterior_brasil,1,BRASIL_EXTERIOR_EXTERIOR_BRASIL,-10.333333,-53.200000,2023-01-08,08-01-2023
131556,1,2023,colombia,amazonas,leticia,7,COLOMBIA_AMAZONAS_LETICIA,-4.212921,-69.942596,2023-01-08,08-01-2023
131557,1,2023,colombia,antioquia,apartado,7,COLOMBIA_ANTIOQUIA_APARTADO,7.884901,-76.622746,2023-01-08,08-01-2023
131558,1,2023,colombia,antioquia,caracoli,1,COLOMBIA_ANTIOQUIA_CARACOLI,6.409276,-74.756698,2023-01-08,08-01-2023
...,...,...,...,...,...,...,...,...,...,...,...
147043,52,2023,colombia,vaupes,mitu,8,COLOMBIA_VAUPES_MITU,1.253850,-70.234558,2023-12-31,31-12-2023
147044,52,2023,colombia,vichada,puerto carreno,1,COLOMBIA_VICHADA_PUERTO CARREÑO,6.190923,-67.484189,2023-12-31,31-12-2023
147045,52,2023,comoras,exterior,exterior_comoras,1,COMORAS_EXTERIOR_EXTERIOR_COMORAS,-12.204518,44.283296,2023-12-31,31-12-2023
147046,52,2023,haiti,exterior,exterior_haiti,1,HAITÍ_EXTERIOR_EXTERIOR_HAITÍ,19.139995,-72.357097,2023-12-31,31-12-2023
147047,52,2023,venezuela,exterior,exterior_venezuela,3,VENEZUELA_EXTERIOR_EXTERIOR_VENEZUELA,8.001871,-66.110932,2023-12-31,31-12-2023

In [45]:
df_geo = pd.read_csv('meteo_colombia/cities_dengue_with_nearest_ciy.csv')
df_geo

,city,state,country,Latitude,Longitude,idx_city,status,nearest_city
0,caracoli,antioquia,colombia,6.409276,-74.756698,COLOMBIA_ANTIOQUIA_CARACOLI,empty,COLOMBIA_ANTIOQUIA_GUATAPE
1,caucasia,antioquia,colombia,7.987758,-75.198374,COLOMBIA_ANTIOQUIA_CAUCASIA,empty,COLOMBIA_CORDOBA_SAN CARLOS
2,el bagre,antioquia,colombia,7.697710,-74.622203,COLOMBIA_ANTIOQUIA_EL BAGRE,empty,COLOMBIA_ANTIOQUIA_YONDO (CASABE)
3,mutata,antioquia,colombia,7.244068,-76.436542,COLOMBIA_ANTIOQUIA_MUTATA,empty,COLOMBIA_ANTIOQUIA_CHIGORODO
4,nechi,antioquia,colombia,8.093808,-74.775199,COLOMBIA_ANTIOQUIA_NECHI,empty,COLOMBIA_SUCRE_EL ROBLE
...,...,...,...,...,...,...,...,...
783,cajibio,cauca,colombia,2.623169,-76.569350,COLOMBIA_CAUCA_CAJIBIO,not_empty,COLOMBIA_CAUCA_CAJIBIO
784,rionegro,antioquia,colombia,6.153617,-75.374169,COLOMBIA_ANTIOQUIA_RIONEGRO,not_empty,COLOMBIA_ANTIOQUIA_RIONEGRO
785,silvia,cauca,colombia,2.611544,-76.378424,COLOMBIA_CAUCA_SILVIA,not_empty,COLOMBIA_CAUCA_SILVIA
786,buenavista,quindio,colombia,4.359948,-75.738723,COLOMBIA_QUINDIO_BUENAVISTA,not_empty,COLOMBIA_QUINDIO_BUENAVISTA
787,exterior_comoras,exterior,comoras,-12.204518,44.283296,COMORAS_EXTERIOR_EXTERIOR_COMORAS,not_empty,COMORAS_EXTERIOR_EXTERIOR_COMORAS

In [46]:
df_geo_s = df_geo[['idx_city', 'nearest_city']].copy()
df_geo_s

                               idx_city                        nearest_city
0           COLOMBIA_ANTIOQUIA_CARACOLI          COLOMBIA_ANTIOQUIA_GUATAPE
1           COLOMBIA_ANTIOQUIA_CAUCASIA         COLOMBIA_CORDOBA_SAN CARLOS
2           COLOMBIA_ANTIOQUIA_EL BAGRE   COLOMBIA_ANTIOQUIA_YONDO (CASABE)
3             COLOMBIA_ANTIOQUIA_MUTATA        COLOMBIA_ANTIOQUIA_CHIGORODO
4              COLOMBIA_ANTIOQUIA_NECHI             COLOMBIA_SUCRE_EL ROBLE
..                                  ...                                 ...
783              COLOMBIA_CAUCA_CAJIBIO              COLOMBIA_CAUCA_CAJIBIO
784         COLOMBIA_ANTIOQUIA_RIONEGRO         COLOMBIA_ANTIOQUIA_RIONEGRO
785               COLOMBIA_CAUCA_SILVIA               COLOMBIA_CAUCA_SILVIA
786         COLOMBIA_QUINDIO_BUENAVISTA         COLOMBIA_QUINDIO_BUENAVISTA
787  COMORAS_EXTERIOR_EXTERIOR_COMORAS   COMORAS_EXTERIOR_EXTERIOR_COMORAS

[788 rows x 2 columns]

In [47]:
df_merge = df_dengue.merge(df_geo_s, left_on='idx_city', right_on='idx_city', how='left')
df_merge

,SEMANA,ANO,country,state,city,count,idx_city,Latitude,Longitude,date,week,nearest_city
0,1,2023,aruba,exterior,exterior_aruba,1,ARUBA_EXTERIOR_EXTERIOR_ARUBA,12.501363,-69.961848,2023-01-08,08-01-2023,ARUBA_EXTERIOR_EXTERIOR_ARUBA
1,1,2023,brasil,exterior,exterior_brasil,1,BRASIL_EXTERIOR_EXTERIOR_BRASIL,-10.333333,-53.200000,2023-01-08,08-01-2023,NaN
2,1,2023,colombia,amazonas,leticia,7,COLOMBIA_AMAZONAS_LETICIA,-4.212921,-69.942596,2023-01-08,08-01-2023,COLOMBIA_AMAZONAS_LETICIA
3,1,2023,colombia,antioquia,apartado,7,COLOMBIA_ANTIOQUIA_APARTADO,7.884901,-76.622746,2023-01-08,08-01-2023,COLOMBIA_ANTIOQUIA_APARTADO
4,1,2023,colombia,antioquia,caracoli,1,COLOMBIA_ANTIOQUIA_CARACOLI,6.409276,-74.756698,2023-01-08,08-01-2023,COLOMBIA_ANTIOQUIA_GUATAPE
...,...,...,...,...,...,...,...,...,...,...,...,...
15489,52,2023,colombia,vaupes,mitu,8,COLOMBIA_VAUPES_MITU,1.253850,-70.234558,2023-12-31,31-12-2023,COLOMBIA_VAUPES_MITU
15490,52,2023,colombia,vichada,puerto carreno,1,COLOMBIA_VICHADA_PUERTO CARREÑO,6.190923,-67.484189,2023-12-31,31-12-2023,COLOMBIA_VICHADA_PUERTO CARREÑO
15491,52,2023,comoras,exterior,exterior_comoras,1,COMORAS_EXTERIOR_EXTERIOR_COMORAS,-12.204518,44.283296,2023-12-31,31-12-2023,COMORAS_EXTERIOR_EXTERIOR_COMORAS
15492,52,2023,haiti,exterior,exterior_haiti,1,HAITÍ_EXTERIOR_EXTERIOR_HAITÍ,19.139995,-72.357097,2023-12-31,31-12-2023,NaN
15493,52,2023,venezuela,exterior,exterior_venezuela,3,VENEZUELA_EXTERIOR_EXTERIOR_VENEZUELA,8.001871,-66.110932,2023-12-31,31-12-2023,NaN

In [48]:
df_merge['date'] = pd.to_datetime(df_merge['date'])
df_merge['week'] = df_merge['date'].dt.to_period('W').apply(lambda r: r.start_time)

In [49]:
df_merge.dropna(subset=['nearest_city'], inplace=True)
df_merge.reset_index(drop=True, inplace=True)
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15197 entries, 0 to 15196
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SEMANA        15197 non-null  int64
 1   ANO           15197 non-null  int64
 2   country       15197 non-null  object
 3   state         15197 non-null  object
 4   city          15197 non-null  object
 5   count         15197 non-null  int64
 6   idx_city      15197 non-null  object
 7   Latitude      15197 non-null  float64
 8   Longitude     15197 non-null  float64
 9   date          15197 non-null  datetime64[ns]
 10  week          15197 non-null  datetime64[ns]
 11  nearest_city  15197 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(3), object(5)
memory usage: 1.4+ MB

In [50]:
df_merge_s = df_merge[['idx_city', 'week','count','Latitude', 'Longitude','nearest_city']].copy()

In [51]:
files_csv

['ARUBA_EXTERIOR_EXTERIOR_ARUBA.csv',
 'COLOMBIA_AMAZONAS_LETICIA.csv',
 'COLOMBIA_ANTIOQUIA_AMAGA.csv',
 'COLOMBIA_ANTIOQUIA_ANTIOQUIA.csv',
 'COLOMBIA_ANTIOQUIA_ANZA.csv',
 'COLOMBIA_ANTIOQUIA_APARTADO.csv',
 'COLOMBIA_ANTIOQUIA_BELLO.csv',
 'COLOMBIA_ANTIOQUIA_BOLIVAR.csv',
 'COLOMBIA_ANTIOQUIA_CALDAS.csv',
 'COLOMBIA_ANTIOQUIA_CAREPA.csv',
 'COLOMBIA_ANTIOQUIA_CARMEN DE VIBORAL.csv',
 'COLOMBIA_ANTIOQUIA_CHIGORODO.csv',
 'COLOMBIA_ANTIOQUIA_COCORNA.csv',
 'COLOMBIA_ANTIOQUIA_COPACABANA.csv',
 'COLOMBIA_ANTIOQUIA_EBEJICO.csv',
 'COLOMBIA_ANTIOQUIA_ENVIGADO.csv',
 'COLOMBIA_ANTIOQUIA_GIRARDOTA.csv',
 'COLOMBIA_ANTIOQUIA_GUATAPE.csv',
 'COLOMBIA_ANTIOQUIA_ITAGUI.csv',
 'COLOMBIA_ANTIOQUIA_LA CEJA.csv',
 'COLOMBIA_ANTIOQUIA_LA ESTRELLA.csv',
 'COLOMBIA_ANTIOQUIA_MEDELLIN.csv',
 'COLOMBIA_ANTIOQUIA_RIONEGRO.csv',
 'COLOMBIA_ANTIOQUIA_SABANETA.csv',
 'COLOMBIA_ANTIOQUIA_SAN JERONIMO.csv',
 'COLOMBIA_ANTIOQUIA_SANTA BARBARA.csv',
 'COLOMBIA_ANTIOQUIA_TURBO.csv',
 'COLOMBIA_ANTIOQUIA_VENECIA.csv',
 'COLOMBIA_ANTIOQUIA_YONDO (CASABE).csv',
 'COLOMBIA_ARAUCA_ARAUCA.csv',
 'COLOMBIA_ARAUCA_FORTUL.csv',
 'COLOMBIA_ARAUCA_SARAVENA.csv',
 'COLOMBIA_ARAUCA_TAME.csv',
 'COLOMBIA_ATLANTICO_BARANOA.csv',
 'COLOMBIA_ATLANTICO_BARRANQUILLA.csv',
 'COLOMBIA_ATLANTICO_GALAPA.csv',
 'COLOMBIA_ATLANTICO_JUAN DE ACOSTA.csv',
 'COLOMBIA_ATLANTICO_MALAMBO.csv',
 'COLOMBIA_ATLANTICO_PALMAR DE VARELA.csv',
 'COLOMBIA_ATLANTICO_PONEDERA.csv',
 'COLOMBIA_ATLANTICO_PUERTO COLOMBIA.csv',
 'COLOMBIA_ATLANTICO_SABANAGRANDE.csv',
 'COLOMBIA_ATLANTICO_SABANALARGA.csv',
 'COLOMBIA_ATLANTICO_SANTO TOMAS.csv',
 'COLOMBIA_ATLANTICO_SOLEDAD.csv',
 'COLOMBIA_ATLANTICO_TUBARA.csv',
 'COLOMBIA_ATLANTICO_USIACURI.csv',
 'COLOMBIA_BOLIVAR_ARJONA.csv',
 'COLOMBIA_BOLIVAR_CARTAGENA.csv',
 'COLOMBIA_BOLIVAR_CLEMENCIA.csv',
 'COLOMBIA_BOLIVAR_TURBACO.csv',
 'COLOMBIA_BOLIVAR_TURBANA.csv',
 'COLOMBIA_BOLIVAR_VILLANUEVA.csv',
 'COLOMBIA_BOYACA_CUBARA.csv',
 'COLOMBIA_CALDAS_MANIZALES.csv',
 'COLOMBIA_CALDAS_MANZANARES.csv',
 'COLOMBIA_CALDAS_MARQUETALIA.csv',
 'COLOMBIA_CALDAS_NEIRA.csv',
 'COLOMBIA_CALDAS_SAMANA.csv',
 'COLOMBIA_CALDAS_VICTORIA.csv',
 'COLOMBIA_CALDAS_VILLAMARIA.csv',
 'COLOMBIA_CAQUETA_EL DONCELLO.csv',
 'COLOMBIA_CAQUETA_EL PAUJIL.csv',
 'COLOMBIA_CAQUETA_FLORENCIA.csv',
 'COLOMBIA_CAQUETA_LA MONTANITA.csv',
 'COLOMBIA_CAQUETA_MILAN.csv',
 'COLOMBIA_CAQUETA_MORELIA.csv',
 'COLOMBIA_CAUCA_CAJIBIO.csv',
 'COLOMBIA_CAUCA_EL TAMBO.csv',
 'COLOMBIA_CAUCA_GUAPI.csv',
 'COLOMBIA_CAUCA_PIENDAMO.csv',
 'COLOMBIA_CAUCA_POPAYAN.csv',
 'COLOMBIA_CAUCA_ROSAS.csv',
 'COLOMBIA_CAUCA_SILVIA.csv',
 'COLOMBIA_CAUCA_TIMBIO.csv',
 'COLOMBIA_CAUCA_TIMBIQUI.csv',
 'COLOMBIA_CESAR_MANAURE BALCON DEL CESAR.csv',
 'COLOMBIA_CESAR_ROBLES (LA PAZ).csv',
 'COLOMBIA_CESAR_SAN DIEGO.csv',
 'COLOMBIA_CESAR_VALLEDUPAR.csv',
 'COLOMBIA_CHOCO_ATRATO.csv',
 'COLOMBIA_CHOCO_BAHIA SOLANO (MUTIS).csv',
 'COLOMBIA_CHOCO_LLORO.csv',
 'COLOMBIA_CHOCO_MEDIO ATRATO.csv',
 'COLOMBIA_CHOCO_QUIBDO.csv',
 'COLOMBIA_CHOCO_SAN JOSE DEL PALMAR.csv',
 'COLOMBIA_CORDOBA_CERETE.csv',
 'COLOMBIA_CORDOBA_CHINU.csv',
 'COLOMBIA_CORDOBA_CIENAGA DE ORO.csv',
 'COLOMBIA_CORDOBA_COTORRA.csv',
 'COLOMBIA_CORDOBA_MONTERIA.csv',
 'COLOMBIA_CORDOBA_SAN ANDRES SOTAVENTO.csv',
 'COLOMBIA_CORDOBA_SAN CARLOS.csv',
 'COLOMBIA_CORDOBA_SAN PELAYO.csv',
 'COLOMBIA_CORDOBA_TUCHIN.csv',
 'COLOMBIA_CUNDINAMARCA_AGUA DE DIOS.csv',
 'COLOMBIA_CUNDINAMARCA_CACHIPAY.csv',
 'COLOMBIA_CUNDINAMARCA_CAJICA.csv',
 'COLOMBIA_CUNDINAMARCA_CHIA.csv',
 'COLOMBIA_CUNDINAMARCA_FACATATIVA.csv',
 'COLOMBIA_CUNDINAMARCA_FUNZA.csv',
 'COLOMBIA_CUNDINAMARCA_GIRARDOT.csv',
 'COLOMBIA_CUNDINAMARCA_GUATAQUI.csv',
 'COLOMBIA_CUNDINAMARCA_GUAYABETAL.csv',
 'COLOMBIA_CUNDINAMARCA_JERUSALEN.csv',
 'COLOMBIA_CUNDINAMARCA_LA CALERA.csv',
 'COLOMBIA_CUNDINAMARCA_MOSQUERA.csv',
 'COLOMBIA_CUNDINAMARCA_NARIÑO.csv',
 'COLOMBIA_CUNDINAMARCA_NILO.csv',
 'COLOMBIA_CUNDINAMARCA_RICAURTE.csv',
 'COLOMBIA_CUNDINAMARCA_SAN ANTONIO DE TEQUENDAMA.csv',
 'COLOMBIA_CUNDINAMARCA_SAN FRANCISCO.csv',
 'COLOMBIA_CUNDINAMARCA_SIBATE.csv',
 'COLOMBIA_CUNDINAMARCA_SOACHA.csv',
 'COLOMBIA_CUNDINAMARCA_SUBACHOQUE.csv',
 'COLOMBIA_CUNDINAMARCA_SUPATA.csv',
 'COLOMBIA_CUNDINAMARCA_TENA.csv',
 'COLOMBIA_CUNDINAMARCA_TENJO.csv',
 'COLOMBIA_CUNDINAMARCA_TOCAIMA.csv',
 'COLOMBIA_CUNDINAMARCA_TOCANCIPA.csv',
 'COLOMBIA_CUNDINAMARCA_UBAQUE.csv',
 'COLOMBIA_CUNDINAMARCA_ZIPACON.csv',
 'COLOMBIA_CUNDINAMARCA_ZIPAQUIRA.csv',
 'COLOMBIA_GUAINIA_PUERTO INIRIDA.csv',
 'COLOMBIA_GUAJIRA_LA JAGUA DEL PILAR.csv',
 'COLOMBIA_GUAJIRA_RIOHACHA.csv',
 'COLOMBIA_GUAJIRA_URUMITA.csv',
 'COLOMBIA_GUAJIRA_VILLANUEVA.csv',
 'COLOMBIA_GUAVIARE_EL RETORNO.csv',
 'COLOMBIA_GUAVIARE_SAN JOSE DEL GUAVIARE.csv',
 'COLOMBIA_HUILA_AIPE.csv',
 'COLOMBIA_HUILA_CAMPOALEGRE.csv',
 'COLOMBIA_HUILA_NEIVA.csv',
 'COLOMBIA_HUILA_PALERMO.csv',
 'COLOMBIA_HUILA_RIVERA.csv',
 'COLOMBIA_HUILA_SANTA MARIA.csv',
 'COLOMBIA_HUILA_TELLO.csv',
 'COLOMBIA_HUILA_VILLAVIEJA.csv',
 'COLOMBIA_MAGDALENA_CIENAGA.csv',
 'COLOMBIA_MAGDALENA_SANTA MARTHA.csv',
 'COLOMBIA_META_ACACIAS.csv',
 'COLOMBIA_META_CASTILLA LA NUEVA.csv',
 'COLOMBIA_META_CUMARAL.csv',
 'COLOMBIA_META_GUAMAL.csv',
 'COLOMBIA_META_PUERTO CONCORDIA.csv',
 'COLOMBIA_META_RESTREPO.csv',
 'COLOMBIA_META_VILLAVICENCIO.csv',
 'COLOMBIA_NARIÑO_EL CHARCO.csv',
 'COLOMBIA_NARIÑO_EL TAMBO.csv',
 'COLOMBIA_NARIÑO_FRANCISCO PIZARRO (SALAHONDA).csv',
 'COLOMBIA_NARIÑO_IPIALES.csv',
 'COLOMBIA_NARIÑO_LA UNION.csv',
 'COLOMBIA_NARIÑO_PASTO.csv',
 'COLOMBIA_NARIÑO_POLICARPA.csv',
 'COLOMBIA_NARIÑO_SAN LORENZO.csv',
 'COLOMBIA_NARIÑO_SANDONA.csv',
 'COLOMBIA_NARIÑO_SANTA BARBARA (ISCUANDE).csv',
 'COLOMBIA_NARIÑO_TAMINANGO.csv',
 'COLOMBIA_NARIÑO_TUMACO.csv',
 'COLOMBIA_NORTE SANTANDER_BOCHALEMA.csv',
 'COLOMBIA_NORTE SANTANDER_CHINACOTA.csv',
 'COLOMBIA_NORTE SANTANDER_DURANIA.csv',
 'COLOMBIA_NORTE SANTANDER_EL ZULIA.csv',
 'COLOMBIA_NORTE SANTANDER_GRAMALOTE.csv',
 'COLOMBIA_NORTE SANTANDER_LOS PATIOS.csv',
 'COLOMBIA_NORTE SANTANDER_PUERTO SANTANDER.csv',
 'COLOMBIA_NORTE SANTANDER_SAN CAYETANO.csv',
 'COLOMBIA_NORTE SANTANDER_SANTIAGO.csv',
 'COLOMBIA_NORTE SANTANDER_VILLA DEL ROSARIO.csv',
 'COLOMBIA_PUTUMAYO_PUERTO ASIS.csv',
 'COLOMBIA_PUTUMAYO_PUERTO CAICEDO.csv',
 'COLOMBIA_PUTUMAYO_SAN MIGUEL (LA DORADA).csv',
 'COLOMBIA_QUINDIO_ARMENIA.csv',
 'COLOMBIA_QUINDIO_BUENAVISTA.csv',
 'COLOMBIA_QUINDIO_CALARCA.csv',
 'COLOMBIA_QUINDIO_CIRCASIA.csv',
 'COLOMBIA_QUINDIO_CORDOBA.csv',
 'COLOMBIA_QUINDIO_LA TEBAIDA.csv',
 'COLOMBIA_QUINDIO_MONTENEGRO.csv',
 'COLOMBIA_QUINDIO_QUIMBAYA.csv',
 'COLOMBIA_QUINDIO_SALENTO.csv',
 'COLOMBIA_RISARALDA_BALBOA.csv',
 'COLOMBIA_RISARALDA_DOSQUEBRADAS.csv',
 'COLOMBIA_RISARALDA_LA CELIA.csv',
 'COLOMBIA_RISARALDA_LA VIRGINIA.csv',
 'COLOMBIA_RISARALDA_PEREIRA.csv',
 'COLOMBIA_SAN ANDRES_PROVIDENCIA.csv',
 'COLOMBIA_SAN ANDRES_SAN ANDRES.csv',
 'COLOMBIA_SANTANDER_BARRANCABERMEJA.csv',
 'COLOMBIA_SANTANDER_BETULIA.csv',
 'COLOMBIA_SANTANDER_BUCARAMANGA.csv',
 'COLOMBIA_SANTANDER_FLORIDABLANCA.csv',
 'COLOMBIA_SANTANDER_GIRON.csv',
 'COLOMBIA_SANTANDER_LEBRIJA.csv',
 'COLOMBIA_SANTANDER_LOS SANTOS.csv',
 'COLOMBIA_SANTANDER_MATANZA.csv',
 'COLOMBIA_SANTANDER_PIEDECUESTA.csv',
 'COLOMBIA_SANTANDER_SAN VICENTE DE CHUCURI.csv',
 'COLOMBIA_SANTANDER_TONA.csv',
 'COLOMBIA_SANTANDER_ZAPATOCA.csv',
 'COLOMBIA_SUCRE_BUENAVISTA.csv',
 'COLOMBIA_SUCRE_CHALAN.csv',
 'COLOMBIA_SUCRE_COLOSO (RICAURTE).csv',
 'COLOMBIA_SUCRE_COROZAL.csv',
 'COLOMBIA_SUCRE_EL ROBLE.csv',
 'COLOMBIA_SUCRE_GALERAS (NUEVA GRANADA).csv',
 'COLOMBIA_SUCRE_LOS PALMITOS.csv',
 'COLOMBIA_SUCRE_MORROA.csv',
 'COLOMBIA_SUCRE_OVEJAS.csv',
 'COLOMBIA_SUCRE_PALMITO.csv',
 'COLOMBIA_SUCRE_SAMPUES.csv',
 'COLOMBIA_SUCRE_SAN JUAN DE BETULIA.csv',
 'COLOMBIA_SUCRE_SAN PEDRO.csv',
 'COLOMBIA_SUCRE_SINCE.csv',
 'COLOMBIA_SUCRE_SINCELEJO.csv',
 'COLOMBIA_SUCRE_TOLUVIEJO.csv',
 'COLOMBIA_TOLIMA_ALVARADO.csv',
 'COLOMBIA_TOLIMA_ANZOATEGUI.csv',
 'COLOMBIA_TOLIMA_ARMERO (GUAYABAL).csv',
 'COLOMBIA_TOLIMA_CAJAMARCA.csv',
 'COLOMBIA_TOLIMA_CARMEN DE APICALA.csv',
 'COLOMBIA_TOLIMA_COELLO.csv',
 'COLOMBIA_TOLIMA_ESPINAL.csv',
 'COLOMBIA_TOLIMA_FALAN.csv',
 'COLOMBIA_TOLIMA_FLANDES.csv',
 'COLOMBIA_TOLIMA_FRESNO.csv',
 'COLOMBIA_TOLIMA_GUAMO.csv',
 'COLOMBIA_TOLIMA_HONDA.csv',
 'COLOMBIA_TOLIMA_IBAGUE.csv',
 'COLOMBIA_TOLIMA_ICONONZO.csv',
 'COLOMBIA_TOLIMA_MARIQUITA.csv',
 'COLOMBIA_TOLIMA_MELGAR.csv',
 'COLOMBIA_TOLIMA_MURILLO.csv',
 'COLOMBIA_TOLIMA_PALOCABILDO.csv',
 'COLOMBIA_TOLIMA_PIEDRAS.csv',
 'COLOMBIA_TOLIMA_SAN LUIS.csv',
 'COLOMBIA_TOLIMA_SUAREZ.csv',
 'COLOMBIA_TOLIMA_VALLE DE SAN JUAN.csv',
 'COLOMBIA_TOLIMA_VILLAHERMOSA.csv',
 'COLOMBIA_VALLE_ALCALA.csv',
 'COLOMBIA_VALLE_ANSERMANUEVO.csv',
 'COLOMBIA_VALLE_BUENAVENTURA.csv',
 'COLOMBIA_VALLE_CAICEDONIA.csv',
 'COLOMBIA_VALLE_CALI.csv',
 'COLOMBIA_VALLE_CANDELARIA.csv',
 'COLOMBIA_VALLE_CARTAGO.csv',
 'COLOMBIA_VALLE_EL AGUILA.csv',
 'COLOMBIA_VALLE_EL CERRITO.csv',
 'COLOMBIA_VALLE_GINEBRA.csv',
 'COLOMBIA_VALLE_GUACARI.csv',
 'COLOMBIA_VALLE_LA CUMBRE.csv',
 'COLOMBIA_VALLE_LA UNION.csv',
 'COLOMBIA_VALLE_LA VICTORIA.csv',
 'COLOMBIA_VALLE_OBANDO.csv',
 'COLOMBIA_VALLE_PALMIRA.csv',
 'COLOMBIA_VALLE_PRADERA.csv',
 'COLOMBIA_VALLE_RESTREPO.csv',
 'COLOMBIA_VALLE_TORO.csv',
 'COLOMBIA_VALLE_VIJES.csv',
 'COLOMBIA_VALLE_YUMBO.csv',
 'COLOMBIA_VAUPES_MITU.csv',
 'COLOMBIA_VICHADA_PUERTO CARREÑO.csv',
 'COMORAS_EXTERIOR_EXTERIOR_COMORAS .csv',
 'COSTA RICA_EXTERIOR_COSTA RICA.csv',
 'CURACAO_EXTERIOR_CURACAO.csv',
 'ECUADOR_EXTERIOR_EXTERIOR_ECUADOR.csv',
 'ESTADOS UNIDOS DE AMÉRICA_EXTERIOR_EXTERIOR_ESTADOS UNIDOS.csv',
 'FINLANDIA_EXTERIOR_FINLANDIA.csv',
 'GUATEMALA_EXTERIOR_EXTERIOR_GUATEMALA.csv',
 'INDIA_EXTERIOR_EXTERIOR_INDIA.csv']

In [52]:
weather_weekly_path = 'meteo_colombia/cities_weekly/'
files_csv = os.listdir(weather_weekly_path)
df_weather = pd.DataFrame()
for file in files_csv:
    df_temp = pd.read_csv(weather_weekly_path + file)
    df_temp['idx'] = file.split('.')[0]
    df_weather = pd.concat([df_weather, df_temp], ignore_index=True)

df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14310 entries, 0 to 14309
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   week    14310 non-null  object
 1   tavg    14310 non-null  float64
 2   tmin    14310 non-null  float64
 3   tmax    14310 non-null  float64
 4   prcp    14310 non-null  float64
 5   wdir    14310 non-null  float64
 6   wspd    14310 non-null  float64
 7   pres    14246 non-null  float64
 8   idx     14310 non-null  object
dtypes: float64(7), object(2)
memory usage: 1006.3+ KB

In [53]:
df_weather['week'] = pd.to_datetime(df_weather['week'])
df_weather['week'] = df_weather['week'].dt.to_period('W').apply(lambda r: r.start_time)

In [54]:
df_merge_l = df_merge_s.merge(df_weather, left_on=['nearest_city', 'week'], right_on=['idx', 'week'], how='left')

In [56]:
df_merge_l.drop(columns=['idx'], inplace=True)

In [58]:
df_merge_l.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15197 entries, 0 to 15196
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   idx_city      15197 non-null  object
 1   week          15197 non-null  datetime64[ns]
 2   count         15197 non-null  int64
 3   Latitude      15197 non-null  float64
 4   Longitude     15197 non-null  float64
 5   nearest_city  15197 non-null  object
 6   tavg          15197 non-null  float64
 7   tmin          15197 non-null  float64
 8   tmax          15197 non-null  float64
 9   prcp          15197 non-null  float64
 10  wdir          15197 non-null  float64
 11  wspd          15197 non-null  float64
 12  pres          15123 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(1), object(2)
memory usage: 1.5+ MB

In [59]:
df_merge_l.reset_index(drop=True, inplace=True)

In [60]:
# cities that are not self in nearest_city
is_self = []
for i in range(len(df_merge_l)):
    if df_merge_l['idx_city'][i] == df_merge_l['nearest_city'][i]:
        is_self.append('Self')
    else:
        is_self.append('Not Self')
df_merge_l['is_self'] = is_self

In [71]:
df_self_cities = df_merge_l[df_merge_l['is_self'] == 'Self'].copy()
df_self_cities = df_self_cities[['idx_city', 'Latitude', 'Longitude']].copy()
df_self_cities.drop_duplicates(subset=['idx_city'], inplace=True)
df_self_cities.reset_index(drop=True, inplace=True)
df_self_cities.rename(columns={'Latitude': 'Latidude_nearest', 'Longitude':'Longitude_nearest'}, inplace=True)
df_self_cities.rename(columns={'idx_city': 'nearest_city'}, inplace=True)

In [72]:
df_merge_xl = df_merge_l.merge(df_self_cities, left_on='nearest_city', right_on='nearest_city', how='left')
df_merge_xl

,idx_city,week,count,Latitude,Longitude,nearest_city,tavg,tmin,tmax,prcp,wdir,wspd,pres,is_self,Latidude_nearest,Longitude_nearest
0,ARUBA_EXTERIOR_EXTERIOR_ARUBA,2023-01-02,1,12.501363,-69.961848,ARUBA_EXTERIOR_EXTERIOR_ARUBA,26.685714,24.400000,29.785714,0.814286,87.000000,23.242857,1014.271429,Self,12.501363,-69.961848
1,COLOMBIA_AMAZONAS_LETICIA,2023-01-02,7,-4.212921,-69.942596,COLOMBIA_AMAZONAS_LETICIA,25.228571,22.985714,29.171429,8.528571,56.000000,4.800000,1010.985714,Self,-4.212921,-69.942596
2,COLOMBIA_ANTIOQUIA_APARTADO,2023-01-02,7,7.884901,-76.622746,COLOMBIA_ANTIOQUIA_APARTADO,27.628571,22.357143,30.885714,5.000000,180.714286,8.214286,1012.014286,Self,7.884901,-76.622746
3,COLOMBIA_ANTIOQUIA_CARACOLI,2023-01-02,1,6.409276,-74.756698,COLOMBIA_ANTIOQUIA_GUATAPE,15.342857,12.314286,21.514286,6.171429,54.000000,6.771429,1025.657143,Not Self,6.234218,-75.161745
4,COLOMBIA_ANTIOQUIA_CAREPA,2023-01-02,2,7.798452,-76.746039,COLOMBIA_ANTIOQUIA_CAREPA,27.628571,22.357143,30.885714,5.000000,180.714286,8.214286,1012.014286,Self,7.798452,-76.746039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15192,COLOMBIA_VALLE_YUMBO,2023-12-25,66,3.583466,-76.495222,COLOMBIA_VALLE_YUMBO,23.514286,19.657143,29.728571,9.957143,53.142857,8.314286,1017.057143,Self,3.583466,-76.495222
15193,COLOMBIA_VALLE_ZARZAL,2023-12-25,7,4.393943,-76.070647,COLOMBIA_VALLE_LA VICTORIA,23.142857,19.214286,29.714286,8.900000,110.142857,5.300000,1014.942857,Not Self,4.523250,-76.035783
15194,COLOMBIA_VAUPES_MITU,2023-12-25,8,1.253850,-70.234558,COLOMBIA_VAUPES_MITU,25.814286,22.842857,31.428571,10.571429,173.428571,4.642857,1011.928571,Self,1.253850,-70.234558
15195,COLOMBIA_VICHADA_PUERTO CARREÑO,2023-12-25,1,6.190923,-67.484189,COLOMBIA_VICHADA_PUERTO CARREÑO,29.942857,22.914286,34.114286,0.042857,149.571429,8.185714,1010.742857,Self,6.190923,-67.484189
15196,COMORAS_EXTERIOR_EXTERIOR_COMORAS,2023-12-25,1,-12.204518,44.283296,COMORAS_EXTERIOR_EXTERIOR_COMORAS,28.857143,27.157143,30.628571,1.357143,27.857143,14.314286,1011.685714,Self,-12.204518,44.283296

In [74]:
import math
def euclidean_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the Euclidean distance between two points on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.asin(math.sqrt(a))
    r = 6371  # Radius of earth in kilometers. Use 3956 for miles
    return c * r

In [75]:
df_merge_xl.reset_index(drop=True, inplace=True)
distances = []
for i in range(len(df_merge_xl)):
    lat1 = df_merge_xl['Latitude'][i]
    lon1 = df_merge_xl['Longitude'][i]
    lat2 = df_merge_xl['Latidude_nearest'][i]
    lon2 = df_merge_xl['Longitude_nearest'][i]
    distance = euclidean_distance(lat1, lon1, lat2, lon2)
    distances.append(distance)

In [76]:
df_merge_xl['distance'] = distances

In [78]:
df_merge_xl.drop(columns=['Latidude_nearest', 'Longitude_nearest', 'is_self', 'nearest_city'], inplace=True)
df_merge_xl.to_csv('gold/dengue_geo_weather.csv', index=False)